services:
  - type: web
    name: financial-researcher
    runtime: python
    rootDir: 3_crew/financial_researcher
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
    plan: free
